### ISSUE TITLE
(-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by Linda-L** [xiaoyufenfei/Efficient-Segmentation-Networks#19]
/home/ll/anaconda3/envs/t1.2/bin/python /media/ll/L/Efficient-Segmentation-Networks/train.py
1.2
=====> input size:(512, 1024)
Namespace(batch_size=4, classes=19, cuda=True, dataset='cityscapes', gpus='0', input_size='512,1024', logFile='log.txt', lr=0.0005, lr_schedule='warmpoly', max_epochs=1000, model='FastSCNN', num_cycles=1, num_workers=4, optim='adam', poly_exp=0.9, random_mirror=True, random_scale=True, resume='', savedir='./checkpoint/', train_type='trainval', use_focal=True, use_label_smoothing=False, use_lovaszsoftmax=False, use_ohem=False, warmup_factor=0.3333333333333333, warmup_iters=500)
=====> use gpu id: '0'
=====> set Global Seed:  1234
=====> building network
=====> computing network parameters and FLOPs
the number of parameters: 1138051 ==> 1.14 M
find file:  ./dataset/inform/cityscapes_inform.pkl
length of dataset:  122
length of dataset:  59
=====> Dataset statistics
data['classWeights']:  [ 1.4705521  9.505282  10.492059  10.492059  10.492059  10.492059
 10.492059  10.492059  10.492059  10.492059  10.492059  10.492059
 10.492059  10.492059  10.492059  10.492059  10.492059  10.492059
  5.131664 ]
mean and std:  [72.3924   82.90902  73.158325] [45.319206 46.15292  44.91484 ]
single GPU for training
=====> beginning training
=====> the number of iterations per epoch:  30
Traceback (most recent call last):
  File "/media/ll/L/Efficient-Segmentation-Networks/train.py", line 401, in <module>
    train_model(args)
  File "/media/ll/L/Efficient-Segmentation-Networks/train.py", line 218, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "/media/ll/L/Efficient-Segmentation-Networks/train.py", line 301, in train
    for iteration, batch in enumerate(train_loader, 0):
  File "/home/ll/anaconda3/envs/t1.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ll/anaconda3/envs/t1.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ll/anaconda3/envs/t1.2/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/t1.2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ll/anaconda3/envs/t1.2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ll/anaconda3/envs/t1.2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/ll/L/Efficient-Segmentation-Networks/dataset/cityscapes.py", line 64, in __getitem__
    label = cv2.resize(label, None, fx=f_scale, fy=f_scale, interpolation=cv2.INTER_NEAREST)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-7m_g9lbm/opencv/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Process finished with exit code 1

**Comment by GitHubmalajava** [comment]
I use the dataset is cityscapes but have a error:  ValueError: num_samples should be a positive integer value, but got num_samples=0  .what should be do
