### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by lgqfhwy** [xiaoyufenfei/Efficient-Segmentation-Networks#2]
when train on 18epoch, it would report error:
```
Traceback (most recent call last):
  File "train.py", line 396, in <module>
    train_model(args)
  File "train.py", line 213, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "train.py", line 328, in train
    optimizer.step()
  File "/home/lgq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/home/lgq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/home/lgq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 36, in wrapper
    return func(*args, **kwargs)
  [Previous line repeated 991 more times]
  File "/home/lgq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/optim/adam.py", line 69, in step
    state = self.state[p]
  File "/home/lgq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/tensor.py", line 393, in __hash__
    return id(self)
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I found that you put WarmupPolyLR in every iters, it would make every iter call WarmupPolyLR, maybe it cause the error.

**Comment by xiaoyufenfei** [comment]
It's your personal question, you should specify the --warmup_iters, for me, there is no any problem

**Comment by lgqfhwy** [comment]
In my opinion, you could not put  WarmupPolyLR in every iter.
 1. There is no code on github like this, include pytorch document not do it. And it could bring burden to system. It would report errors due to the difference of pytorch version.
 2. There is no need to do this. You put WarmupPolyLR in every iter because you want to use variable 
cur_iter. But cur_iter does not need to pass on. When you define WarmupPolyLR, you inherit torch.optim.lr_scheduler._LRScheduler, there is a variable self._step_count in _LRScheduler, it has a same purpose to cur_iter.So you could just write like:
```
    def get_lr(self):
        self.cur_iter = self._step_count - 2
        if self.cur_iter <= self.warmup_iters:
            alpha = self.cur_iter / self.warmup_iters
            warmup_factor = self.warmup_factor * (1 - alpha) + alpha
            # print(self.base_lrs[0]*warmup_factor)
            return [lr * warmup_factor for lr in self.base_lrs]
        else:
            return [self.eta_min + (base_lr - self.eta_min) *
                    math.pow(1 - (self.cur_iter - self.warmup_iters) / (self.T_max - self.warmup_iters),
                             self.power) for base_lr in self.base_lrs]
```
or you could just use (self._step_count - 2) to replace self.cur_iter. After do this, you only need to call  WarmupPolyLR after train once, it could have same effect to your origin code, but it reduce many times call function WarmupPolyLR.
What's more, thank you for your code and happy new year :)

**Comment by xiaoyufenfei** [comment]
Happy New Year ! Thank you for you suggestion.

**Comment by dronefreak** [comment]
Hi @lgqfhwy 
Were you able to resolve this issue because I am facing it as of now.
Please let me know your workaround.
I did try increasing the max recursion depth by using the `sys` library in python, but it still gets stuck at th 9th epoch for me.

**Comment by xiaoyufenfei** [comment]
Maybe this way can help you. 
https://github.com/xiaoyufenfei/Efficient-Segmentation-Networks/blob/0f0c32e7af3463d381cb184a158ff60e16f7fb9a/train.py#L25

**Comment by favoMJ** [comment]
the reason for this is 
`        if args.lr_schedule == 'poly':
            lambda1 = lambda epoch: math.pow((1 - (args.cur_iter / args.max_iter)), args.poly_exp)
            scheduler = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lambda1)
        elif args.lr_schedule == 'warmpoly':
            scheduler = WarmupPolyLR(optimizer, T_max=args.max_iter, cur_iter=args.cur_iter, warmup_factor=1.0 / 3,
                                 warmup_iters=args.warmup_iters, power=0.9)`

Just turn it into a global variable
