### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by GREENtt** [xiaoyufenfei/Efficient-Segmentation-Networks#27]
Traceback (most recent call last):
  File "D:/Code/CodePycharm/Deep_Learning/segment/Efficient-Segmentation-Networks-master/train.py", line 409, in <module>
    train_model(args)
  File "D:/Code/CodePycharm/Deep_Learning/segment/Efficient-Segmentation-Networks-master/train.py", line 222, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "D:/Code/CodePycharm/Deep_Learning/segment/Efficient-Segmentation-Networks-master/train.py", line 336, in train
    loss.backward()
  File "D:\Environment\Anaconda\envs\lmffnet\lib\site-packages\torch\tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Environment\Anaconda\envs\lmffnet\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

Process finished with exit code 1

can you help me? please.

**Comment by zhiwenj-HNU** [comment]
cuda version is incorrect. You need to reinstall CUDA 9.0 or 9.2

**Comment by zhiwenj-HNU** [comment]
cuda version is incorrect. You need to reinstall CUDA 9.0 or 9.2
