### ISSUE TITLE
ESNet: Error after 161 iterations

### ISSUE THREAD

**Issue by shifangtian** [xiaoyufenfei/Efficient-Segmentation-Networks#7]
Such like this:
=====> epoch[161/300] iter: (526/1329) 	cur_lr: 0.000251 loss: 0.445 time:0.67
=====> epoch[161/300] iter: (527/1329) 	cur_lr: 0.000251 loss: 0.196 time:0.58
Traceback (most recent call last):
  File "D:/my/torch-gpu/Efficient-Segmentation-Networks/Efficient-Segmentation-Networks/train.py", line 398, in <module>
    train_model(args)
  File "D:/my/torch-gpu/Efficient-Segmentation-Networks/Efficient-Segmentation-Networks/train.py", line 215, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "D:/my/torch-gpu/Efficient-Segmentation-Networks/Efficient-Segmentation-Networks/train.py", line 329, in train
    loss.backward()
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\autograd\__init__.py", line 87, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "D:\deeplearning\anaconda\envs\torch-gpu\lib\site-packages\torch\autograd\__init__.py", line 28, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

**Comment by xiaoyufenfei** [comment]
Can you provide more information? you solved it?

**Comment by shifangtian** [comment]
> Can you provide more information? you solved it?

no,it still exists.my cuda is 9.0 ,gpu:gtx1660,dataset:cityscapes,batchsize:2

**Comment by xiaoyufenfei** [comment]
sorry, I have check, no any problem
